import '../styles/globals.css'
import Head from 'next/head'
import CssBaseline from '@material-ui/core/CssBaseline';

function MyApp({ Component, pageProps }) {

  return (<>
    <Head>
      <title>Soft core motors</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
    </Head>
    <CssBaseline />
    <Component {...pageProps} /> </>)
}

export default MyApp
